# Generated by Django 4.1.2 on 2022-10-15 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodRe', '0002_baiviet_comment_cuahang_danhgia_khachhang_sanpham_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuahang',
            old_name='ten_cua_hang',
            new_name='ten_CH',
        ),
    ]
