# Generated by Django 4.1.2 on 2022-10-15 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodRe', '0003_rename_ten_cua_hang_cuahang_ten_ch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='Image',
            field=models.ImageField(upload_to='SanPham/%Y/%m'),
        ),
    ]
