# Generated by Django 4.1.2 on 2022-10-15 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodRe', '0004_alter_sanpham_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baiviet',
            old_name='san_pham',
            new_name='ten_SP',
        ),
        migrations.RemoveField(
            model_name='sanpham',
            name='Image',
        ),
        migrations.AddField(
            model_name='baiviet',
            name='Image',
            field=models.ImageField(default=None, upload_to='foodRe/%Y/%m'),
        ),
        migrations.AddField(
            model_name='comment',
            name='Image',
            field=models.ImageField(default=None, upload_to='foodRe/%Y/%m'),
        ),
        migrations.AddField(
            model_name='cuahang',
            name='Image',
            field=models.ImageField(default=None, upload_to='foodRe/%Y/%m'),
        ),
        migrations.AddField(
            model_name='danhgia',
            name='Image',
            field=models.ImageField(default=None, upload_to='foodRe/%Y/%m'),
        ),
        migrations.AddField(
            model_name='khachhang',
            name='Image',
            field=models.ImageField(default=None, upload_to='foodRe/%Y/%m'),
        ),
    ]
