# Generated by Django 4.1.2 on 2022-10-15 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodRe', '0005_rename_san_pham_baiviet_ten_sp_remove_sanpham_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baiviet',
            name='noi_dung',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='price',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='ten_CH',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodRe.cuahang'),
        ),
    ]
