# Generated by Django 4.1.2 on 2022-10-15 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodRe', '0006_baiviet_noi_dung_sanpham_price_alter_sanpham_ten_ch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baiviet',
            old_name='noi_dung',
            new_name='content',
        ),
    ]
