# Generated by Django 4.1.2 on 2022-10-15 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodRe', '0007_rename_noi_dung_baiviet_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='danhgia',
            name='Image',
        ),
    ]
