# Generated by Django 4.1.2 on 2022-10-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodRe', '0008_remove_danhgia_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='Image',
            field=models.ImageField(default=None, upload_to='foodRe/%Y/%m'),
        ),
    ]
