# Generated by Django 4.1.2 on 2022-10-15 15:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodRe', '0009_sanpham_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baiviet',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
