# Generated by Django 4.1.2 on 2022-10-15 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodRe', '0010_alter_baiviet_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khachhang',
            name='AccountType',
        ),
        migrations.AlterField(
            model_name='baiviet',
            name='ten_KH',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='khach_hang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='danhgia',
            name='khach_hang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='ten_CH',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='cuaHang',
        ),
        migrations.DeleteModel(
            name='khachHang',
        ),
    ]
