# Generated by Django 4.1.2 on 2022-10-16 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodRe', '0011_remove_khachhang_accounttype_alter_baiviet_ten_kh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baiviet',
            name='ten_SP',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
