# Generated by Django 4.1.2 on 2022-10-16 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodRe', '0013_rename_ten_sp_baiviet_san_pham_alter_sanpham_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='cuaHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_date', models.DateTimeField(auto_now_add=True)),
                ('Update_date', models.DateTimeField(auto_now=True)),
                ('Active', models.BooleanField(default=True)),
                ('Image', models.ImageField(default=None, upload_to='foodRe/%Y/%m')),
                ('ten_CH', models.CharField(max_length=255, unique=True)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
