# Generated by Django 4.1.2 on 2022-10-16 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodRe', '0014_cuahang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baiviet',
            name='san_pham',
        ),
    ]
