# Generated by Django 4.1 on 2022-10-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodRe', '0015_remove_baiviet_san_pham'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuahang',
            name='role',
        ),
        migrations.RemoveField(
            model_name='sanpham',
            name='Image',
        ),
        migrations.AddField(
            model_name='cuahang',
            name='dia_chi',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='cuahang',
            name='gio_mo_cua',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
