# Generated by Django 4.1 on 2022-10-16 10:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodRe', '0016_remove_cuahang_role_remove_sanpham_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='Active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='Created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sanpham',
            name='Image',
            field=models.ImageField(default=None, upload_to='foodRe/%Y/%m'),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='Update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
