# Generated by Django 4.1 on 2022-10-16 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodRe', '0017_sanpham_active_sanpham_created_date_sanpham_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sanpham',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='baiviet',
            old_name='Active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='cuahang',
            old_name='Active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='sanpham',
            old_name='Active',
            new_name='active',
        ),
    ]
