# Generated by Django 4.1 on 2022-10-19 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodRe', '0018_alter_sanpham_options_rename_active_baiviet_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='danhgia',
            old_name='Active',
            new_name='active',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='active',
        ),
        migrations.AlterField(
            model_name='comment',
            name='bai_viet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodRe.baiviet'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='khach_hang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
