# Generated by Django 4.1 on 2022-10-21 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodRe', '0020_remove_danhgia_active_alter_danhgia_chat_luong_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewBaiViet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_date', models.DateTimeField(auto_now_add=True)),
                ('Update_date', models.DateTimeField(auto_now=True)),
                ('views', models.IntegerField(default=0)),
                ('bai_viet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodRe.baiviet')),
            ],
        ),
    ]
