# Generated by Django 4.1 on 2022-10-21 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodRe', '0021_viewbaiviet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cuaHang',
        ),
    ]
