# Generated by Django 4.1 on 2022-10-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodRe', '0022_delete_cuahang'),
    ]

    operations = [
        migrations.CreateModel(
            name='cuaHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_date', models.DateTimeField(auto_now_add=True)),
                ('Update_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('Image', models.ImageField(default=None, upload_to='foodRe/%Y/%m')),
                ('ten_CH', models.CharField(max_length=255, unique=True)),
                ('dia_chi', models.CharField(max_length=255, unique=True)),
                ('gio_mo_cua', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
