# Generated by Django 4.1 on 2022-10-23 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodRe', '0024_viewsanpham_delete_viewbaiviet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewsanpham',
            name='san_pham',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='foodRe.sanpham'),
        ),
    ]
